// AUTOGENERATED by @nxweb/builder@3.6.0-rc.54

declare namespace NodeJS {
  type ProcessPkg = { readonly $: Record<string, unknown>; } & Record<string, any>;

  interface Process {
    /**
     * The process.pkg property returns an object containing the package manifest (package.json)
     */
    readonly pkg: ProcessPkg
  }

  interface ProcessEnv {
    // @ts-expect-error
    readonly $: Record<string, unknown>;
    readonly NODE_ENV: 'development' | 'production' | 'test';
    readonly APP_URL: string;
  }
}

interface Window {
  readonly NX: {
    readonly env: Record<string, string | undefined>;
  }
}

declare module '*.avif' {
  const src: string;
  export default src;
}

declare module '*.avif?inline' {
  const src: string;
  export default src;
}

declare module '*.avif?raw' {
  const src: string;
  export default src;
}

declare module '*.bmp' {
  const src: string;
  export default src;
}

declare module '*.bmp?inline' {
  const src: string;
  export default src;
}

declare module '*.bmp?raw' {
  const src: string;
  export default src;
}

declare module '*.gif' {
  const src: string;
  export default src;
}

declare module '*.gif?inline' {
  const src: string;
  export default src;
}

declare module '*.gif?raw' {
  const src: string;
  export default src;
}

declare module '*.jpg' {
  const src: string;
  export default src;
}

declare module '*.jpg?inline' {
  const src: string;
  export default src;
}

declare module '*.jpg?raw' {
  const src: string;
  export default src;
}

declare module '*.jpeg' {
  const src: string;
  export default src;
}

declare module '*.jpeg?inline' {
  const src: string;
  export default src;
}

declare module '*.jpeg?raw' {
  const src: string;
  export default src;
}

declare module '*.png' {
  const src: string;
  export default src;
}

declare module '*.png?inline' {
  const src: string;
  export default src;
}

declare module '*.png?raw' {
  const src: string;
  export default src;
}

declare module '*.webp' {
    const src: string;
    export default src;
}

declare module '*.webp?inline' {
  const src: string;
  export default src;
}

declare module '*.webp?raw' {
  const src: string;
  export default src;
}

declare module '*.svg' {
  const src: string;
  export default src;
}

declare module '*.svg?inline' {
  const src: string;
  export default src;
}

declare module '*.svg?raw' {
  const src: string;
  export default src;
}

declare module '*.svg?react' {
  const src: import('react').ComponentType<import('react').SVGProps<import('react').ReactSVGElement>>;
  export default src;
}

declare module '*.svg?icon' {
  const src: import('react').ComponentType<import('react').SVGProps<import('react').ReactSVGElement> & { size?: number | string }>;
  export default src;
}

declare module '*.module.css' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module '*.module.scss' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module '*.module.sass' {
  const classes: { readonly [key: string]: string };
  export default classes;
}
